In [2]:
from sklearn.datasets import load_iris
from sklearn import tree
import numpy as np
import random

In [3]:
iris = load_iris()

In [4]:
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [17]:
ind = np.arange(150)

In [18]:
ind

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149])

In [19]:
random.shuffle(ind)
iris.data = iris.data[ind]
iris.target = iris.target[ind]

In [20]:
iris.target

array([1, 2, 0, 0, 1, 1, 2, 1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 2, 2, 2, 0, 2, 0, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 1, 0, 2,
       1, 2, 2, 2, 0, 2, 1, 0, 2, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 2, 1, 1,
       0, 1, 1, 2, 2, 1, 0, 0, 0, 0, 2, 1, 0, 2, 2, 0, 2, 2, 0, 1, 2, 1,
       1, 1, 2, 2, 0, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 0, 2, 2, 2, 2, 0, 0,
       1, 0, 2, 2, 2, 1, 2, 0, 1, 1, 2, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 0,
       1, 0, 1, 2, 2, 0, 1, 2, 0, 1, 1, 0, 0, 1, 1, 1, 2, 1])

In [21]:
iris_train_x = iris.data[:-50]
iris_test_x = iris.data[-50:]
iris_train_y = iris.target[:-50]
iris_test_y = iris.target[-50:]

In [22]:
clf = tree.DecisionTreeClassifier()

In [23]:
clf = clf.fit(iris_train_x, iris_train_y)

In [24]:
predict = clf.predict(iris_test_x)

In [25]:
print(predict)

[2 0 2 0 2 2 2 2 0 0 1 0 2 2 2 1 2 0 2 1 2 0 0 0 2 1 0 1 0 0 0 0 1 0 1 2 1
 0 1 2 0 1 1 0 0 1 1 1 2 2]


In [26]:
numOfCorrectPrediction = (predict == iris_test_y).sum()
numOfDataSamples = len(iris_test_y)

In [27]:
print(numOfCorrectPrediction/ float(numOfDataSamples))

0.92
