# FreqDist Entropy with nltk 

In [23]:
import nltk, math

In [2]:
freqdist = nltk.FreqDist(['male','male','female','male'])

In [3]:
freqdist

FreqDist({'male': 3, 'female': 1})

In [4]:
probs = [freqdist.freq(i) for i in freqdist ]
print(probs)

[0.75, 0.25]


<h4> # Return the base-10 logarithm of x. This is usually more accurate than log(x, 10) <h4>

In [14]:
s = (p*math.log(p,2) for p in probs)
s

<generator object <genexpr> at 0x00000283077ADFC0>

In [15]:
s = -sum(p*math.log(p,2) for p in probs)
s

0.8112781244591328

In [16]:
import nltk, math

In [20]:
def entropy(labels):
    freqdist = nltk.FreqDist(labels)
    probs = [freqdist.freq(p) for p in freqdist]
    return freqdist, probs, -sum(p*math.log(p,2) for p in probs)

In [21]:
print(entropy(['male','male','female','male']))

(FreqDist({'male': 3, 'female': 1}), [0.75, 0.25], 0.8112781244591328)


# Cross Entropy Check

In [ ]:
import numpy as np

# Array의 하나하나가 각각의 example이다
# 이 Example에 대해선 이렇게 예측했는데 
# 그리고 곱하면 - > 결국 엔트로피값은 작아야 좋으니깐, 작으면 좋다

In [26]:
predictions = np.array([[0.25,0.25,0.25,0.25],[0.01,0.01,0.01,0.96]])

In [27]:
predictions

array([[0.25, 0.25, 0.25, 0.25],
       [0.01, 0.01, 0.01, 0.96]])

In [28]:
targets = np.array([[0,0,0,1],[0,0,0,1]])

In [29]:
targets

array([[0, 0, 0, 1],
       [0, 0, 0, 1]])

# np.clip

<h4> Given an interval, values outside the interval are clipped to the interval edges. For example, if an interval of [0, 1] is specified, values smaller than 0 become 0, and values larger than 1 become 1. </h4>

In [31]:
epsilon = 1e-12
epsilon

1e-12

In [33]:
predictions = np.clip(predictions, epsilon, 1.-epsilon)
predictions

array([[0.25, 0.25, 0.25, 0.25],
       [0.01, 0.01, 0.01, 0.96]])

In [34]:
N = predictions.shape[0]

In [35]:
N

2

In [41]:
-np.sum(np.sum(targets*np.log(predictions)))/N

0.7135581778200729

 
- 브라질 vs 아르헨에서 실제로 누가 이길 지를 미리 알 수 없다.
- P(x)를 모르기 때문에 KL-divergence를 minimize하려면, E(-log(Q(x)))를 minimize
- 이때 E(-log(Q(x)))를 cross entropy라고 부른다.
- E(-log(Q(x))) = -∑ P(x) * log(Q(x))
- 그런데 E(-log(Q(x))) 를 구할 때 각 Q(x)에 대한 가중치로 P(x)가 필요한데, 이때 P(x)는 - 우리가 가진 데이터의 비율을 사용한다. (empirical distribution)
- 예를 들어, 위의 축구경기 예에서 cross entropy는 다음과 같다.

# E(-log(Q(x))) = -∑ P(x) * log(Q(x))


In [42]:
def cross_entropy(predictions, targets, epsilon=1e-12):
        predictions = np.clip(predictions, epsilon, 1.-epsilon)
        N = predictions.shape[0]
        ce = -np.sum(targets*np.log(predictions))/N
        return ce

In [44]:
cross_entropy(predictions, targets)

0.7135581778200729