# Neural Network

In [2]:
import numpy as np
from activation import sigmoid

In [5]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

A1 = np.dot(X, W1) + B1
A1

array([0.3, 0.7, 1.1])

In [6]:
Z1 = sigmoid(A1)

In [7]:
print(A1)
print(Z1)

[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]


In [8]:
W2 = np.array([[0.1, 0.4],[0.2, 0.5],[0.3, 0.6]])
W2

array([[0.1, 0.4],
       [0.2, 0.5],
       [0.3, 0.6]])

In [9]:
B3 = np.array([0.1, 0.2])
A3 = np.dot(Z1, W2) +  B3

In [13]:
def identity_function(x):
    return x

In [15]:
Y = identity_function(A3)
print(A3)
print(Y)

[0.51615984 1.21402696]
[0.51615984 1.21402696]


# 3 Layer nueral network

In [16]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5],[0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    
    return network

In [23]:
def foward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)
    
    return y

In [24]:
network = init_network()
print(network)

{'W1': array([[0.1, 0.3, 0.5],
       [0.2, 0.4, 0.6]]), 'b1': array([0.1, 0.2, 0.3]), 'W2': array([[0.1, 0.4],
       [0.2, 0.5],
       [0.3, 0.6]]), 'b2': array([0.1, 0.2]), 'W3': array([[0.1, 0.3],
       [0.2, 0.4]]), 'b3': array([0.1, 0.2])}


In [26]:
x = np.array([1.0, 0.5])
y = foward(network, x)
print(y)

[0.31682708 0.69627909]


In [ ]:
# exp(x)값이 너무 커져서 NaN이 나오는걸 방지하기위해서 max값을 뺸다
# 어짜피 softmax는 전체 결과값들에서 차지하는 비율을 보기때문에 상관없다

In [28]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a=  np.sum(exp_a)
    y = exp_a/sum_exp_a
    return y

# MINIST Neural Network

In [47]:
import sys, os
import numpy as np
from dataset.mnist import load_mnist
from PIL import Image

(x_train, t_train), (x_test, t_test) = load_mnist(flatten = True, normalize = False)

print(x_train.shape)
print(t_train.shape)
print(x_test.shape)
print(t_test.shape)

# 훈련이미지 60000장, 시험이미지 10000장
# MNIST 이미지 데이터는 28 X 28 크기

(60000, 784)
(60000,)
(10000, 784)
(10000,)


In [48]:
def img_show(img):
    pil_img = Image.fromarray(np.uint8(img))
    display(pil_img)

In [49]:
img = x_train[0]
label = t_train[0]
print(label)

5


In [50]:
print(img.shape)

(784,)


In [51]:
img = img.reshape(28,28) # 형상을 원래 이미지의 크기로 변형

In [52]:
print(img.shape)

(28, 28)


In [53]:
img_show(img)

In [54]:
# pickle = 가중치량 / bias값이 이미 저장되어있는 라이브러리
import pickle
from activation import sigmoid, softmax

In [55]:
def get_data():
    (x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=True)
    return x_test, t_test

In [56]:
def init_network():
    # rb = readByte / wb = writeByte
    with open('sample_weight.pkl','rb') as f:
        network = pickle.load(f)
    return network

In [57]:
def predict(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = softmax(a3)

    return y

In [58]:
x, t = get_data()
network = init_network()

In [63]:
accuracy_cnt = 0
for i in range(len(x)):
    y = predict(network, x[i])
    p = np.argmax(y) # 확률이 가장 높은 원소 획득
    if p == t[i]:
        accuracy_cnt += 1
        
print("Accuracy: ", float(accuracy_cnt)/len(x))    

Accuracy:  0.9352
