In [8]:
def forecast(weather):
    year = weather[:4]
    day = weather[4:8]
    weather = weather[8:]
    print("year is", year, ",day is", day, ",weather is", weather)

In [9]:
forecast("20170622sunny")

year is 2017 ,day is 0622 ,weather is sunny


In [40]:
def isPalindrome(s):
    r = ""
    s = s.replace(" ", "")
    s = s.lower()
    index = len(s)-1
    for i in range(index,-1,-1):
        r = r + s[i]
    if(s==r):
        print("True")
    else:
        print("False")

In [41]:
isPalindrome("A nut for a jar of tuna")

True


In [42]:
isPalindrome("12343211")

False


In [111]:
def spiral(num):
    arr = list()
    for i in range(num):
        line = list()
        for i in range(num):
            line.append(0)
        arr.append(line)
    arr = np.array(arr) 
    
  
    direction = 0  # 0 오른쪽 1 아래쪽 2 왼쪽 3 위쪽
        
    for i in range(0,int(num/2)):   
        #print(arr)
        x = i
        y = i
        # num - i
        n = 0
        for c in range((num-2*i)*4-4):
            #print("X :" , x)
            #print("Y :" , y)
            #print("n :" , n)
            arr[x][y] = n
            n = n + 1
            if(direction==0):
                y = y+1
                if(y==(num-i)):
                    y = y - 1
                    x = x + 1
                    direction = 1
            elif(direction==1):
                x = x + 1
                if(x==(num-i)):
                    x = x -1
                    y = y -1
                    direction = 2
            elif(direction==2):
                y = y -1
                if(y==(i-1)):
                    y = y + 1
                    x = x -1
                    direction = 3
            elif(direction==3):
                x = x - 1
                if(x==(i)):
                    direction = 0
    return arr

In [116]:
s = spiral(6)

In [117]:
print(s)

[[ 0  1  2  3  4  5]
 [19  0  1  2  3  6]
 [18 11  0  1  4  7]
 [17 10  3  2  5  8]
 [16  9  8  7  6  9]
 [15 14 13 12 11 10]]
