In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
M = np.array([[1,2,3],[4,5,6]])
M2 = np.array([[3,3,3],[2,2,2]])

M + M2

array([[4, 5, 6],
       [6, 7, 8]])

In [5]:
np.dot(M,M2.T)

array([[18, 12],
       [45, 30]])

In [6]:
np.column_stack((M,M2))

array([[1, 2, 3, 3, 3, 3],
       [4, 5, 6, 2, 2, 2]])

In [11]:
A = np.eye(3)

In [12]:
v = np.array([[3],[4],[5]])
print(v)

[[3]
 [4]
 [5]]


In [14]:
np.dot(A,v)

array([[3.],
       [4.],
       [5.]])

In [15]:
np.dot(v,v.T)

array([[ 9, 12, 15],
       [12, 16, 20],
       [15, 20, 25]])

In [17]:
print(np.dot(v,A))

ValueError: shapes (3,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0)

In [18]:
A= np.array([[6,0,170],[5, 11, 180],[6, 4, 190], [6, 2, 180]])

In [23]:
A

array([[  6,   0, 170],
       [  5,  11, 180],
       [  6,   4, 190],
       [  6,   2, 180]])

In [40]:
v= np.array([[0],[0],[0.45]])

In [41]:
v

array([[0.  ],
       [0.  ],
       [0.45]])

In [42]:
result = np.dot(A,v)

In [43]:
result

array([[76.5],
       [81. ],
       [85.5],
       [81. ]])

In [47]:
s = np.array([[30, 0],[2.5, 0],[0, 0.45]])
result = np.dot(A,s)

In [48]:
result

array([[180. ,  76.5],
       [177.5,  81. ],
       [190. ,  85.5],
       [185. ,  81. ]])

In [50]:
np.sum(result[:,0])/(len(result[:,0]))

183.125

In [51]:
np.sum(result[:,1])/(len(result[:,1]))

81.0

In [53]:
A = np.array([[1,2],[3,4]])
x = np.array([[5,],[-2]])
print(np.dot(A,x))

[[1]
 [7]]
